theme = "acme"

[editor]
line-number = "relative"
bufferline = "multiple"
rulers = [80, 100]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[keys.insert]
"A-b" = "move_prev_word_start"
"A-f" = "move_next_word_start"
"A-h" = "move_char_left"
"A-l" = "move_char_right"
"A-a" = "goto_line_start"
"A-e" = "goto_line_end"
"A-k" = "move_visual_line_up"
"A-j" = "move_visual_line_down"
