theme = "base16_default"

[editor]
line-number = "relative"
bufferline = "multiple"
rulers = [80, 100]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[keys.insert]
"A-b" = "move_prev_word_start"
"A-f" = "move_next_word_start"
"C-b" = "move_char_left"
"C-f" = "move_char_right"
"C-a" = "goto_line_start"
"C-e" = "goto_line_end"
"C-p" = "move_visual_line_up"
"C-n" = "move_visual_line_down"
